# tests/integration/test_e2e_battle.py
"""End-to-end simulated battle integration test.

Runs a full Gen 9 Random Battle through the real poke_env machinery
(``JevPlayer`` vs ``RandomPlayer``) against a minimal in-process
Showdown-compatible WebSocket server. The Jev decision client is mocked to
return a deterministic, valid choice so the test is hermetic (no network
calls to the Jev provider) while still exercising the complete
connect -> challenge -> battle -> decide -> telemetry -> finish pipeline.
"""
import asyncio
import json
import threading
from typing import Any

import pytest
from websockets.asyncio.server import serve

from poke_env.data import to_id_str
from poke_env.player import RandomPlayer, SimpleHeuristicsPlayer

from jev_showdown.agent import JevPlayer
from jev_showdown.config import Settings
from jev_showdown.decision.opencode_jev import JevSystemOneClient
from jev_showdown.decision.protocol import JevDecisionResponse

BATTLE_FORMAT = "gen9randombattle"
SERVER_PORT = 8000
BATTLE_TAG = "battle-gen9randombattle-1"
MAX_TURNS = 3

# Two fixed six-Pokémon teams (valid Gen 9 species / moves). Random Battle
# teams are generated by the server, so pinning them keeps the battle
# deterministic and legal.
P1_TEAM = [
    {"species": "Garchomp", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Hydreigon", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Heatran", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Excadrill", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Tornadus", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Landorus", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
]
P2_TEAM = [
    {"species": "Chansey", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Lucario", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Volcarona", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Mawile", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Garchomp", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
    {"species": "Talonflame", "moves": ["earthquake", "flamethrower", "roost", "toxic"]},
]


class LocalShowdownServer:
    """A minimal in-process Showdown-compatible WebSocket server.

    It handles the login handshake, routes a single challenge/accept, then
    drives a scripted battle (turn requests + final win) so both poke_env
    players can play and finish a real battle without an external server.
    """

    def __init__(self, host: str = "localhost", port: int = SERVER_PORT,
                 max_turns: int = MAX_TURNS) -> None:
        self.host = host
        self.port = port
        self.max_turns = max_turns
        self.ws_by_id: dict[str, Any] = {}
        self.id_by_ws: dict[Any, str] = {}
        self.raw_by_id: dict[str, str] = {}
        self._queue: asyncio.Queue = asyncio.Queue()
        self._server = None
        self._thread: threading.Thread | None = None
        self._loop: asyncio.AbstractEventLoop | None = None
        self._ready = threading.Event()
        self._stop = threading.Event()

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        if not self._ready.wait(timeout=15):
            raise RuntimeError("Local Showdown server did not start in time")

    def stop(self) -> None:
        self._stop.set()
        if self._loop is not None:
            try:
                self._loop.call_soon_threadsafe(self._shutdown)
            except RuntimeError:
                pass
        if self._thread is not None:
            self._thread.join(timeout=5)

    def _shutdown(self) -> None:
        if self._server is not None:
            self._server.close()

    def _run(self) -> None:
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        try:
            self._loop.run_until_complete(self._serve())
        finally:
            try:
                self._loop.close()
            except Exception:
                pass

    async def _serve(self) -> None:
        async with serve(self._handler, self.host, self.port) as server:
            self._server = server
            self._ready.set()
            await self._battle_driver()

    async def _handler(self, websocket: Any) -> None:
        try:
            await websocket.send("|challstr|0|challenge|nonce")
            uid: str | None = None
            async for raw in websocket:
                msg = str(raw)
                if uid is None:
                    if "/trn " in msg:
                        username = msg.split("/trn ", 1)[1].split(",", 1)[0].strip()
                        uid = to_id_str(username)
                        self.ws_by_id[uid] = websocket
                        self.id_by_ws[websocket] = uid
                        self.raw_by_id[uid] = username
                        await websocket.send(f"|updateuser| {username}|")
                    continue
                if "/trn " in msg:
                    continue
                await self._queue.put((uid, msg))
        except Exception:
            pass

    def _battle_line(self, *lines: str) -> str:
        return "\n".join([f">{BATTLE_TAG}"] + list(lines))

    def _build_init(self, p1_id: str, p2_id: str) -> str:
        p1_name = self.raw_by_id[p1_id]
        p2_name = self.raw_by_id[p2_id]
        return self._battle_line(
            "|init|battle",
            "|tier|Gen 9 Random Battle",
            "|teamsize|p1|6",
            "|teamsize|p2|6",
            f"|player|p1|{p1_name}|0",
            f"|player|p2|{p2_name}|0",
            "|start",
        )

    def _build_request(self, role: str, team: list[dict[str, Any]], turn: int) -> dict:
        side_pokemon = []
        for i, mon in enumerate(team):
            # Ident uses the "p1: Name" form (space at index 3) so poke_env's
            # get_pokemon stores it under the exact ident it is looked up by.
            side_pokemon.append({
                "ident": f"{role}: {mon['species']}",
                "details": mon["species"],
                "active": i == 0,
                "baseAbility": "No Ability",
                "ability": "No Ability",
                "condition": "200/200",
                "item": "",
                "moves": list(mon["moves"]),
                "status": "",
            })
        active_moves = [
            {
                "id": move_id,
                "pp": 10,
                "maxpp": 10,
                "type": "Normal",
                "disabled": False,
                "noClick": False,
                "target": "normal",
                "sourcePosition": 1,
            }
            for move_id in team[0]["moves"]
        ]
        return {
            "side": {"id": role, "name": "", "pokemon": side_pokemon},
            "active": [{
                "moves": active_moves,
                "trapped": False,
                "canMegaEvo": False,
                "canZMove": False,
                "canDynamax": False,
                "canTerastallize": False,
                "maybeTrapped": False,
                "mustMove": True,
            }],
            "forceSwitch": [False],
            "rqid": f"req{turn}",
        }

    def _parse_challenge_target(self, msg: str) -> str:
        return msg.split("/challenge ", 1)[1].split(",", 1)[0].strip()

    async def _battle_driver(self) -> None:
        q = self._queue
        # Wait for both players to log in.
        while len(self.ws_by_id) < 2:
            await asyncio.sleep(0.02)

        # Wait for the challenge.
        challenger = None
        while challenger is None:
            uid, msg = await q.get()
            if uid is not None and "/challenge" in msg:
                challenger = uid
                target = self._parse_challenge_target(msg)
                target_ws = self.ws_by_id.get(target)
                if target_ws is not None:
                    payload = json.dumps(
                        {"challengesFrom": {challenger: BATTLE_FORMAT}}
                    )
                    await target_ws.send(f"|updatechallenges|{payload}")

        # Wait for the accept.
        acceptor = None
        while acceptor is None:
            uid, msg = await q.get()
            if uid is not None and "/accept" in msg:
                acceptor = uid

        p1_id, p2_id = challenger, acceptor
        p1_ws = self.ws_by_id[p1_id]
        p2_ws = self.ws_by_id[p2_id]

        # Battle initialisation for both players.
        init = self._build_init(p1_id, p2_id)
        await p1_ws.send(init)
        await p2_ws.send(init)
        await asyncio.sleep(0.2)

        # Turn loop.
        for turn in range(1, self.max_turns + 1):
            req1 = self._build_request("p1", P1_TEAM, turn)
            req2 = self._build_request("p2", P2_TEAM, turn)
            await p1_ws.send(self._battle_line(f"|request|{json.dumps(req1)}"))
            await p2_ws.send(self._battle_line(f"|request|{json.dumps(req2)}"))

            choices: set[str] = set()
            while len(choices) < 2:
                uid, msg = await q.get()
                if uid is not None and "/choose" in msg:
                    choices.add(uid)

            if turn == self.max_turns:
                winner = self.raw_by_id[p1_id]
                win_line = self._battle_line(f"|win|{winner}")
                await p1_ws.send(win_line)
                await p2_ws.send(win_line)
                break
            else:
                turn_line = self._battle_line(f"|turn|{turn + 1}")
                await p1_ws.send(turn_line)
                await p2_ws.send(turn_line)

        # Give the players time to process the terminal message before
        # tearing the server down.
        await asyncio.sleep(0.5)


def _make_settings() -> Settings:
    return Settings(
        showdown_username=None,
        showdown_password=None,
        showdown_server_url="localhost:8000",
        jev_endpoint="https://opencode.ai/zen/v1/systemone",
        jev_model="jev-1.13-free",
        jev_auth_token="Bearer public",
        jev_timeout_seconds=5.0,
        battle_format="gen9randombattle",
        dashboard_port=8000,
    )


@pytest.mark.parametrize("opponent_cls", [RandomPlayer, SimpleHeuristicsPlayer])
@pytest.mark.asyncio
async def test_full_simulated_battle_against_provider_free_opponents(opponent_cls):
    settings = _make_settings()

    # Mock the Jev decision client so no real provider call is made. The
    # mock returns a valid, deterministic choice: the first legal candidate.
    jev_client = JevSystemOneClient(settings)

    async def fake_evaluate_decision(
        state: dict[str, Any],
        criteria: dict[str, str],
        instructions: str = "Choose the strongest legal action.",
        *,
        deadline_monotonic: float | None = None,
    ) -> JevDecisionResponse:
        first_candidate_key = next(iter(criteria), None)
        probabilities = (
            {first_candidate_key: 0.9} if first_candidate_key is not None else {}
        )
        return JevDecisionResponse(
            model="jev-1.13-free",
            choice=first_candidate_key,
            confidence=0.9,
            probabilities=probabilities,
            latency_ms=120.0,
        )

    jev_client.evaluate_decision = fake_evaluate_decision

    events_received: list[dict[str, Any]] = []

    server = LocalShowdownServer(port=SERVER_PORT)
    server.start()
    try:
        jev_player = JevPlayer(
            settings=settings,
            jev_client=jev_client,
            on_turn_event=events_received.append,
            battle_format=BATTLE_FORMAT,
        )
        random_opponent = opponent_cls(battle_format=BATTLE_FORMAT)

        await asyncio.wait_for(
            jev_player.battle_against(random_opponent, n_battles=1),
            timeout=60,
        )
    finally:
        server.stop()

    # The battle ran to completion.
    assert jev_player.n_finished_battles == 1

    # Telemetry was dispatched for at least one turn.
    assert len(events_received) > 0
    json.dumps(events_received, allow_nan=False)

    first_evt = events_received[0]
    # The payload is a typed TURN_DECISION event carrying the snapshot and
    # the order validation result.
    assert first_evt["type"] == "TURN_DECISION"
    assert first_evt["is_fallback"] is False
    assert "snapshot" in first_evt
    assert "validation" in first_evt
    assert first_evt["request"]["rqid"] is not None
    assert first_evt["fingerprint"]["candidate_ids"]
    # The snapshot always reports six opponent team slots (fog of war).
    assert len(first_evt["snapshot"]["opponent"]["team_slots"]) == 6
